# Copyright (c) 2018 Benjamin Levy
#
# This file is part of FollowTheBeat.
#
# FollowTheBeat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FollowTheBeat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FollowTheBeat. If not, see <http://www.gnu.org/licenses/>.

language: haxe
os:
  - linux
cache:
  directories:
  - "/home/travis/haxe/lib"
before_install:
  - sudo apt-get -qq update
install:
  # Install HaxeFlixel
  - echo $(haxelib config)
  - travis_wait haxelib --always install flixel
  - yes | travis_wait haxelib run lime setup
  - travis_wait haxelib --always set hxcpp 3.4.64

  # Install Android SDK, platform-tools, and API level 19
  - export ANDROID_HOME=$(pwd)/android-sdk
  - mkdir $ANDROID_HOME
  # SDK version must be >= 25.2.3 for sdkmanager and < 25.3.0 for tools/ant
  # This is one of the few versions that actually works :)
  - wget http://dl-ssl.google.com/android/repository/tools_r25.2.3-linux.zip
  - unzip -q tools_r25.2.3-linux.zip
  - mv tools $ANDROID_HOME
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin
  - yes | sdkmanager platform-tools
  - yes | sdkmanager "build-tools;24.0.1"
  - travis_wait sdkmanager "platforms;android-19"

  # Install Android NDK
  - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -q android-ndk-r13b-linux-x86_64.zip
  - export ANDROID_NDK=$(pwd)/android-ndk-r13b
  - export ANDROID_NDK_HOME=$ANDROID_NDK
  - export PATH=$PATH:$ANDROID_NDK

  # Install Apache Ant
  - sudo apt-get install -y ant

  # Install Java JDK
  - sudo apt-get install -y oracle-java8-installer

  - printf "n\nn\nn\nn\n$ANDROID_HOME\n$ANDROID_NDK\n$ANT_HOME\n/usr/lib/jvm/java-8-openjdk\n" | haxelib run lime setup android
script:
  - travis_wait haxelib run lime build android
  - travis_wait haxelib run lime build linux
  - travis_wait haxelib run lime build mac
  - travis_wait haxelib run lime build windows
before_deploy:
  - travis_wait haxelib run lime deploy linux
  - travis_wait haxelib run lime deploy mac
  - travis_wait haxelib run lime deploy windows
deploy:
  provider: releases
  api_key:
    secure: FViyItrbNNKejz1qHggiIWkSscWZR0lhfFGS6kaWn135CoH16XdE+eotPUDO2DGs+toQDQK+ZuX9Ipqn8tA3pyS4DYpQJLCBweeU0obiGTVoT4eHtI0+ImHvZ5799zCvXGf5Uyzo565dayrl4cXtDNE0DNF6u7pY/jEY8DHCThCARNEA54JBak/FXAORzTAPjFClhgGrSyQJ4aF3z9TzoBhBP/V9fbK1LjM2cRy44VML9uSz7Jxn+epHgW/qknT+j6zqehleWWLtJS0oSTqQhFGP6Ik5sZ8C/kciumRg7OfTKgybUvvUj0UH9G7+gNMhnt0LDU3QvdMt4CGHcUPmwhgkgNKzB2hbFmjEGY0hqlxP7y6nx2N7rKtxf6kfbyM7zXDirS2+rMyGzdnd46y5j9RdJ4Rnh/L8a58Z3KMknvl/ckE6qfA1WOd3vc5ThfuhmGCFPDwjHOteb/2fWc21b0TiXmvfbgIR5Ul+BTCaXFkn7lQdRahugrgJGvv4x86TAft5YHtkbMfwqGLrHBf2wVDKy/M2rXr83PNvGZtKbcNWVRrltkgn5v9Ju67s2ZAR/zFl7w511gikOhmP6imQ+4115p03ONdXsJguIxdc0eUkw/zKvtpuaUUBhyAOh6GZRDVIBvDz+yrvM9iyOm7Ax0aam1AY1KwPxDD8zbSzdOU=
  file_glob: true
  file:
    - export/android/bin/bin/FollowTheBeat-debug.apk
    - export/linux64/cpp/FollowTheBeat*.zip
    - export/mac64/neko/FollowTheBeat*.zip
    - export/windows/neko/FollowTheBeat*.zip
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - rm -f export/android/bin/bin/FollowTheBeat-debug.apk
  - rm -f export/linux64/cpp/FollowTheBeat*.zip
  - rm -f export/mac64/neko/FollowTheBeat*.zip
  - rm -f export/windows/neko/FollowTheBeat*.zip
