# Copyright (c) 2018 Benjamin Levy
#
# This file is part of FollowTheBeat.
#
# FollowTheBeat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FollowTheBeat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FollowTheBeat. If not, see <http://www.gnu.org/licenses/>.

language: haxe
os:
  - linux
  - osx
cache:
  directories:
  - "/home/travis/haxe/lib"
  - "/home/travis/build/mwaldrich/FollowTheBeat/export"
before_install:
  sudo -E ./travis/before_install.sh
install:
  ./travis/install.sh
script:
  ./travis/script.sh
before_deploy:
  ./travis/before_deploy.sh
deploy:
  # Deploy to GitHub Releases
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - export/android/bin/*.apk
      - export/linux/dist/FollowTheBeat*.zip
      - export/mac/dist/FollowTheBeat*.zip
      - export/neko/dist/FollowTheBeat*.zip
    skip_cleanup: true
    on:
      tags: true
    after_deploy:
      - rm -f export/android/bin/*.apk
      - rm -f export/linux/dist/FollowTheBeat*.zip
      - rm -f export/mac/dist/FollowTheBeat*.zip
      - rm -f export/neko/dist/FollowTheBeat*.zip
  # Deploy to GitHub Pages
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: export/html5/bin
    fqdn: followthebeat.io
    project-name: FollowTheBeat
    skip-cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
